version: '3'
services:
  nginx:
    image: "nginx:latest"
    ports:
    - "8081:8081"
    volumes:
    - "./../logs/nginx:/etc/logs/nginx"
    - "./nginx:/etc/nginx/conf.d/"
    - "./../app:/var/www/html"
    command: nginx -g "daemon off;"
    links:
    - fpm
  fpm:
    build: fpm
    volumes:
    - "./../app:/var/www/html"
    links:
    - mysql
  mysql:
    image: "mysql:5.7"
    ports:
    - "3232:3306"
    volumes:
      - "../mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: diufhv8743f8efdgvyfg7w89hfos
      MYSQL_DATABASE: phalcon-test
      MYSQL_USER: ptuser
      MYSQL_PASSWORD: ptpassword